"""
markdown_writer.py — Per-thread file writers for raw transcript and summary.

Output directory: <output_dir>/<platform>/[<team>/]<channel>/<YYYY-MM-DD>/<thread_id>/
  raw.md      — complete verbatim transcript (overwritten in full each run)
  summary.md  — complete re-summary from the LLM (overwritten on each run)

All file writes are atomic: content is written to a .tmp sibling then moved
into place with os.replace() to prevent partial reads.

See DESIGN.md §6 for the full example output format.
"""

from __future__ import annotations

import os
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from src.archive.models import Message, TrackedThread


# ── raw.md — always-overwritten verbatim transcript ─────────────────────────

RAW_HEADER_TEMPLATE = """\
# Thread Transcript

<br>**Platform:** {platform}
<br>**Channel:** {channel}
<br>**Thread ID:** `{thread_id}`
<br>**Subject:** {subject}
<br>**URL:** {url}
<br>**Tracked since:** {tracked_since}

---

"""


def write_raw(
    thread: "TrackedThread",
    all_messages: list["Message"],
    out_dir: Path,
) -> Path:
    """
    Write (or overwrite) <out_dir>/raw.md with the complete verbatim
    transcript of all_messages.

    This file is always regenerated in full from the complete thread history
    stored in Postgres, so overwriting is safe and desirable — mirroring how
    summary.md is handled.

    Writes are atomic via .tmp + os.replace().

    Returns the path to raw.md.
    """
    if not all_messages:
        return out_dir / "raw.md"

    out_dir.mkdir(parents=True, exist_ok=True)
    raw_path = out_dir / "raw.md"

    tracked_since_str = (
        thread.tracked_since.strftime("%Y-%m-%dT%H:%M:%SZ")
        if thread.tracked_since
        else datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    )
    header = RAW_HEADER_TEMPLATE.format(
        platform=thread.platform,
        channel=thread.channel,
        thread_id=thread.thread_id,
        subject=thread.thread_subject or "(no subject)",
        url=thread.thread_url or "(no URL)",
        tracked_since=tracked_since_str,
    )
    message_lines = "".join(_format_message(m) for m in all_messages)
    content = header + message_lines

    _atomic_write(raw_path, content)
    return raw_path


def _format_message(msg: "Message") -> str:
    """Format a single message as a Markdown line for the transcript."""
    try:
        ts = datetime.fromisoformat(msg.timestamp.replace("Z", "+00:00"))
        ts_str = ts.strftime("%Y-%m-%d %H:%M UTC")
    except Exception:
        ts_str = msg.timestamp
    return f"**[{ts_str}] @{msg.author_name}:** {msg.body}\n\n"


# ── summary.md — always-overwritten LLM output ───────────────────────────────

SUMMARY_TEMPLATE = """\
---
generated_at: "{generated_at}"
platform: {platform}
channel: {channel}
{team_line}thread_id: "{thread_id}"
thread_url: "{thread_url}"
message_count: {message_count}
model: {model}
---

# Thread Summary

<br>**Platform:** {platform}
<br>**Channel:** {channel}
<br>**Thread:** [{subject}]({thread_url})

---

{summary_text}

---

*Generated by chat-summarizer · {generated_at}*
"""


def write_summary(
    thread: "TrackedThread",
    summary_text: str,
    out_dir: Path,
    model: str = "unknown",
    message_count: int = 0,
) -> Path:
    """
    Write (or overwrite) <out_dir>/summary.md with the latest LLM output.

    summary_text is the raw LLM response. This file is always regenerated in
    full from the complete thread history stored in Postgres, so overwriting
    is safe and desirable.

    Writes are atomic via .tmp + os.replace().

    Returns the path to summary.md.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    summary_path = out_dir / "summary.md"

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    team_line = f"team: {thread.team}\n" if thread.team else ""

    content = SUMMARY_TEMPLATE.format(
        generated_at=generated_at,
        platform=thread.platform,
        channel=thread.channel,
        team_line=team_line,
        thread_id=thread.thread_id,
        thread_url=thread.thread_url or "",
        message_count=message_count,
        model=model,
        subject=thread.thread_subject or thread.thread_id,
        summary_text=summary_text,
    )

    _atomic_write(summary_path, content)
    return summary_path


# ── internal ──────────────────────────────────────────────────────────────────

def _atomic_write(path: Path, content: str) -> None:
    """Write content to path atomically (tmp file → os.replace)."""
    tmp = str(path) + ".tmp"
    Path(tmp).write_text(content, encoding="utf-8")
    os.replace(tmp, path)
